### ISSUE TITLE
Todo list-15 Nov. to 19 Nov.

### ISSUE THREAD

**Issue by LingyiJia** [LingyiJia/-Msc_DS_FinalProject#2]
- [ ] Start your replication analyses. (Gul will ask Feng to share his excel template). 
 - Replication analyses requires that you read the papers referenced in Section 2.3 of the paper titled "On the Shoulders of the Giants..." and understand them and try to replicate what each study does.
 - In some cases you may not be able to replicate the whole study in a paper. In that case, we will discuss and you should have good scientific justification of why you could not replicate it.
- [ ] Start writing the "Related work" based on the papers (the ones referenced in Section 2.3 of the paper titled "On the Shoulders of the Giants...") that you will have read so far. 

- [ ] Come up some ideas of proposal how you are going to improve, your contributions besides replication.
